### ISSUE TITLE
"TEST" database not being included in default source list

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#179]
in 4.0.0rc5

an authoritative db "TEST" was added (the 19th source in the /etc/irrd.yaml):
```
        TEST:
            authoritative: true
            nrtm_access_list: generic_nrtm_access
            keep_journal: true
```

a maintner and associated person were added to the TEST db.
The maintner was changed to use PGPKEY (and associated key was added).

doing a whois for the maintner MAINT-TBOUDREAU is not found unless I explicitly set the source.
Also `!j` and `!s-lc` do not include the new database.
