### ISSUE TITLE
new data not imported?

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#180]
It appears there is a difference between what is stored on disk, and what is served up through the daemon. Perhaps I configured it wrong?

Every night a new `rpki.db` file is created, and 1 is added to the value in `RPKI.CURRENTSERIAL`, these are copied into place.

```
irrd@irrd01:~/routing_sources/rpki$ cat /home/irrd/dbs/RPKI.CURRENTSERIAL
186
irrd@irrd01:~/routing_sources/rpki$ grep changed: /home/irrd/dbs/rpki.db | sort | uniq
changed:    job@ntt.net 20190127
```

```
hanna:~ job$ whois -h irrd01.ip.gin.ntt.net -- -s RPKI -M 185.0.0.0/8  | grep changed | sort | uniq
changed:        job@ntt.net 20190115
```

This is the configuration, and `RPKI` is listed under `sources_default:` too:

```
        RPKI:
            nrtm_access_list: generic_nrtm_access
            import_serial_source: file:///home/irrd/dbs/RPKI.CURRENTSERIAL
            import_source: file:///home/irrd/dbs/rpki.db
```

**Comment by job** [comment]
on disk serial is 186, on DB i see 181 as latest

```
                  pk                  | source | serial_oldest_seen | serial_newest_seen | serial_oldest_journal | serial_newest_journal | serial_last_export | force_reload | last_error | last_error_timestamp |            created            |            updated
--------------------------------------+--------+--------------------+--------------------+-----------------------+-----------------------+--------------------+--------------+------------+----------------------+-------------------------------+-------------------------------
 492b3f69-3f2b-4bd2-8f0a-c985d277b70c | RPKI   |                181 |                181 |                       |                       |                    | f            |            |                      | 2019-01-16 20:43:12.670088+00 | 2019-01-16 20:50:16.954105+00
```

**Comment by job** [comment]
I set `force_reload` to true, and this triggered an actual reload:

```
hanna:~ job$ whois -h irrd01.ip.gin.ntt.net -- -s RPKI -M 185.0.0.0/8  | grep changed | sort | uniq
changed:        job@ntt.net 20190127
```

Is the expected behaviour that `force_reload` must be set to true to trigger the importer to do something?

**Comment by job** [comment]
I updated the configuration to the following:

```
        RPKI:
            authoritative: false
            import_timer: 300
            nrtm_access_list: generic_nrtm_access
            import_serial_source: file:///home/irrd/dbs/RPKI.CURRENTSERIAL
            import_source: file:///home/irrd/dbs/rpki.db
```

and bumped the CURRENTSERIAL to 187, but it didn't seem to reload the data.
